"use client";
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import Link from 'next/link';
import InvoiceButton from './InvoiceButton';
const statuses=['NEW','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','FAILED','REFUNDED'];
export default function AdminOrderDetailClient({ order }) {
  const [status,setStatus]=useState(String(order.orderStatus||'NEW').toUpperCase()), [saving,setSaving]=useState(false), [error,setError]=useState('');
  const router=useRouter();
  async function update(v){setStatus(v);setSaving(true);setError('');try{const r=await fetch(`/api/admin/orders/${encodeURIComponent(order.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderStatus:v})});const d=await r.json();if(!r.ok)throw Error(d.error||'Status update failed.');router.refresh()}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <div className="admin-detail-wrap"><div className="detail-toolbar"><Link href="/admin/orders">← MANAGE ORDERS</Link><div><InvoiceButton order={order}/><select disabled={saving} value={status} onChange={e=>update(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div></div>{error&&<div className="order-error">{error}</div>}<div className="admin-detail-grid"><section className="detail-panel"><div className="detail-label">ORDER</div><h2>#{order.id}</h2><p>{new Date(order.createdAt).toLocaleString('en-IN')}</p><div className="detail-status-row"><span>{status}</span><span>{order.paymentStatus}</span></div></section><section className="detail-panel"><div className="detail-label">CUSTOMER</div><h3>{order.customer?.name||'Customer'}</h3><p>{order.customer?.email}</p><p>{order.customer?.phone}</p><p>{[order.customer?.address,order.customer?.city,order.customer?.state,order.customer?.pincode].filter(Boolean).join(', ')}</p></section></div><section className="detail-panel"><div className="detail-panel-head"><h3>ORDER ITEMS</h3><strong>₹{Number(order.total||0).toLocaleString('en-IN')}</strong></div><div className="detail-items">{(order.items||[]).map((item,i)=><article key={`${item.id||item.name}-${i}`} className="detail-item"><div className="detail-item-image">{item.image?<img src={item.image} alt=""/>:<b>{item.art||'AVNC'}</b>}</div><div><strong>{item.name}</strong><p>SIZE / {item.size||'—'} · QTY / {item.qty||1}</p>{item.custom&&<div className="custom-design"><b>CUSTOM DESIGN</b><span>Garment: {item.design?.garment||'—'}</span><span>Colour: {item.design?.color||'—'}</span><span>Print text: {item.design?.text||'—'}</span><span>Graphic mark: {item.design?.art||'—'}</span>{item.design?.image&&<img src={item.design.image} alt="Customer artwork"/>}</div>}</div><strong>₹{(Number(item.price||0)*Number(item.qty||1)).toLocaleString('en-IN')}</strong></article>)}</div></section></div>
}
