"use client";
import {useMemo,useState} from 'react';import Link from 'next/link';
import SiteFooter from '../components/SiteFooter';
const colors={Black:'#111',White:'#eee',Cream:'#e9ddc8',Stone:'#aaa69c'};
export default function CreateYours(){const[garment,setGarment]=useState('TEE');const[color,setColor]=useState('Black');const[size,setSize]=useState('M');const[placement,setPlacement]=useState('FRONT');const[text,setText]=useState('YOUR IDEA');const[art,setArt]=useState('A/N');const[image,setImage]=useState('');const[added,setAdded]=useState(false);const id=useMemo(()=>`custom-${Date.now()}`,[color,size,garment,placement]);
 function add(){const c=JSON.parse(localStorage.getItem('avancy-cart')||'[]');const key=`${id}-${Date.now()}`;c.push({key,id,name:`CUSTOM ${garment}`,price:699,size,qty:1,custom:true,image,art:'CUSTOM',design:{garment,color,size,placement,text,art,image}});localStorage.setItem('avancy-cart',JSON.stringify(c));dispatchEvent(new Event('avancy-cart-updated'));setAdded(true);setTimeout(()=>setAdded(false),1400)}
 return <main className="creator"><header className="creator-nav"><Link href="/" className="creator-logo">AVANCY / CREATE</Link><Link href="/cart">BAG →</Link></header><section className="creator-grid"><div className="creator-copy"><span>PRINT LAB / 01</span><h1>CREATE<br/><em>YOURS.</em></h1><p>Build a print-on-demand piece. Choose the garment, colour, size, print position and your own artwork or text. Your exact choices travel with the order to our fulfilment control room.</p><div className="creator-field"><label>GARMENT MODEL</label><div className="choice-row">{['TEE','HOODIE'].map(x=><button type="button" className={garment===x?'active':''} onClick={()=>setGarment(x)} key={x}>{x}</button>)}</div></div><div className="creator-field"><label>COLOUR</label><div className="choice-row">{Object.keys(colors).map(x=><button type="button" className={color===x?'active':''} onClick={()=>setColor(x)} key={x}>{x}</button>)}</div></div><div className="creator-field"><label>SIZE</label><div className="choice-row">{['S','M','L','XL','XXL'].map(x=><button type="button" className={size===x?'active':''} onClick={()=>setSize(x)} key={x}>{x}</button>)}</div></div><div className="creator-field"><label>PRINT POSITION</label><div className="choice-row">{['FRONT','BACK','CHEST'].map(x=><button type="button" className={placement===x?'active':''} onClick={()=>setPlacement(x)} key={x}>{x}</button>)}</div></div><div className="creator-field"><label>PRINT TEXT</label><input value={text} maxLength={28} onChange={e=>setText(e.target.value)}/></div><div className="creator-field"><label>GRAPHIC MARK</label><input value={art} maxLength={12} onChange={e=>setArt(e.target.value)}/></div><div className="creator-field"><label>UPLOAD YOUR ARTWORK</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>4*1024*1024){alert('Please use an artwork image under 4 MB.');e.target.value='';return}const r=new FileReader();r.onload=()=>setImage(String(r.result));r.readAsDataURL(file)}}/></div><button type="button" className="creator-add" onClick={add}>{added?'ADDED TO BAG ✓':'ADD CUSTOM PIECE — ₹699 →'}</button></div><div className="creator-preview"><div className="preview-label">LIVE PREVIEW / {garment} / {placement}</div><div className="shirt-preview" style={{background:colors[color]}}><div className="shirt-neck"/><div
  className={`print-preview position-${placement.toLowerCase()}`}
  style={{color: color === 'Black' ? '#fff' : '#111'}}
>{image?<img src={image} alt="Your artwork"/>:<><b>{text}</b><span>{art}</span></>}</div></div><div className="preview-note">PRINT AREA / {placement}<br/>Final print may vary slightly by garment. Your artwork and design choices are visible to the Avancy fulfilment team in the admin order.</div></div></section><SiteFooter/></main>}
