"use client";
import Link from 'next/link';import {useEffect,useState} from 'react';import SiteFooter from '../../components/SiteFooter';
const empty={name:'',label:'HOME',phone:'',address:'',city:'',state:'',pincode:'',country:'India'};
export default function Addresses(){const[f,setF]=useState(empty),[a,setA]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState('');
 async function load(){const r=await fetch('/api/account/addresses',{cache:'no-store'});if(!r.ok){setA([]);return}const d=await r.json();setA(d.addresses||[])}useEffect(()=>{load()},[]);const ch=(k,v)=>setF(x=>({...x,[k]:v}));
 function edit(x){setEditing(x.id);setF({name:x.name||'',label:x.label||'HOME',phone:x.phone||'',address:x.address||'',city:x.city||'',state:x.state||'',pincode:x.pincode||'',country:x.country||'India'});setMsg('')}
 async function save(e){e.preventDefault();setMsg('');if(!f.name||!f.address||!f.city||!/^[0-9]{6}$/.test(f.pincode))return setMsg('Please enter a full name, address, city and valid 6-digit pincode.');setBusy(true);try{const r=await fetch('/api/account/addresses',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{...f,id:editing}:f)});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not save address.');setA(x=>editing?(x||[]).map(v=>v.id===editing?d.address:v):[d.address,...(x||[])]);setF(empty);setEditing('');setMsg('Address saved.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function remove(id){if(!confirm('Remove this saved address?'))return;const r=await fetch(`/api/account/addresses?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(r.ok)setA(x=>(x||[]).filter(v=>v.id!==id))}
 return <main className="account-premium"><header className="account-top"><Link href="/account" className="creator-logo">AVANCY<span>COLLECTIVES™</span></Link><Link href="/shop">SHOP →</Link></header><section className="account-hero address-page"><span>SAVED DELIVERY DETAILS</span><h1>SAVED <em>ADDRESSES.</em></h1><div className="address-layout"><form className="address-form premium-form" onSubmit={save}><h2>{editing?'EDIT ADDRESS':'ADD ADDRESS'}</h2>{['name','label','phone','address','city','state','pincode','country'].map(k=><label key={k}>{k==='name'?'FULL NAME':k.toUpperCase()}<input value={f[k]} onChange={e=>ch(k,e.target.value)} required={['name','address','city','pincode'].includes(k)} maxLength={k==='pincode'?6:undefined}/></label>)}<button disabled={busy}>{busy?'SAVING…':editing?'UPDATE ADDRESS →':'SAVE ADDRESS →'}</button>{editing&&<button type="button" className="secondary-btn" onClick={()=>{setEditing('');setF(empty)}}>CANCEL</button>}{msg&&<p className="success">{msg}</p>}</form><div className="address-list"><div className="list-title"><h2>YOUR ADDRESSES</h2><span>{a?.length||0}</span></div>{a?.length?a.map(x=><article className="saved-address" key={x.id}><div><b>{x.name}</b><span>{x.label} · {x.phone||'No phone'}</span><span>{x.address}, {x.city}, {x.state||''} — {x.pincode}, {x.country}</span></div><div className="address-actions"><button onClick={()=>edit(x)}>EDIT</button><button onClick={()=>remove(x.id)}>REMOVE</button></div></article>):<div className="ac-empty">No saved addresses yet.</div>}</div></div></section><SiteFooter/></main>}
